services:
  postgres:
    image: postgres:16
    container_name: ecommerce-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: de_user
      POSTGRES_PASSWORD: de_password
      POSTGRES_DB: ecommerce

    ports:
      - "15432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: